### ISSUE TITLE
A bunch of about:blank entries when I export tabs

### ISSUE THREAD

**Issue by gfajdi** [mortalis13/Tabs-Export-XPI-Android#1]
Hi,
I have a lot of tabs open in my FireFox Android and when I try to export them I get many about:blank entries in the .txt file. I saw the Reload Delay option mentioned on the website but I cannot find it. Can you describe in more detail how do I get to that option to set a longer delay?
Thank you

**Comment by mortalis13** [comment]
Hi. To access the addon options page you should go to Menu -> Add-ons -> Tabs Export.

The Reload Delay is in ms. Test the export with different values that would be enough for the tabs to reload.

Anyway if it's possible to activate each tab manually before exporting (just going to a tab to be sure it's loaded) the export process does not use that delay value and exports all the info instantly.

The problem occurs with the tabs that are restored from the previous Firefox sessions, because they are restored in the background and not loaded explicitly. So the script cannot access neither of the info for that tabs until they are reloaded/activated. 

At this time it's the maximum comfort the addon can achieve due to the limited standards. Hope that in the future it will be possible to get tabs info without checking their state.

**Comment by mortalis13** [comment]
It's possible to use the old addon with previous versions of Firefox which can be downloaded from the Mozilla FTP:
http://ftp.mozilla.org/pub/mobile/releases/

**Comment by gfajdi** [comment]
Got it. I increased the Reload Delay setting to 10,000 ms and now it works as expected. Thank you for your response :-)
