### ISSUE TITLE
Reloading all tabs make firefox crash

### ISSUE THREAD

**Issue by Niluge-KiWi** [mortalis13/Tabs-Export-XPI-Android#2]
Hi,
I was a user of the previous "tabs backup" extension, and since the breaking change I couldn't use the backup feature until I found your new compatible extension here.

Alas, in the meantime I accumulated too much tabs (477 it seems) and the default settings of 2 seconds reload wait generates too much `about:blank`. I tried increasing it but I eventually makes firefox crash.

The whole reload thing is sad, maybe we could ask mozilla to expose the url of discarded tabs? Even the WebIDE has access to all the urls (but I have no idea how to get them from there either..)

**Comment by mortalis13** [comment]
Hi.
I think there was a bug published on mozilla bugsite about the discarded/zombie tabs in WebExtensions standard. So till it's fixed the code cannot access those URL.
I'll check the WebIDE part, if I manage to get a list of tabs from the console.

If you export with 2 seconds wait time it doesn't crash?
Because I would suggest it crashes when there's too much tabs loaded in memory.
With any wait time the addon reloads all dscarded tabs, it just waits after each tab reloaded so its data is available to the next step (like URL).

So maybe try to export 2-3 times the same set of tabs. See if each next export will have more real URLs. Because the code reloads only discarded tabs so it won't reload all the tabs each time.

If not I'll try to add some method to export a portion of tabs at a time so that it not overloads the memory.

**Comment by Niluge-KiWi** [comment]
Thanks, I'll try exporting multiple times with the default wait time and
check if it helps.

**Comment by Niluge-KiWi** [comment]
I tried multiple exports with 2 seconds but the second one makes firefox crash again. This time I got `adb logcat`:
```
07-20 23:33:56.789 16143 16206 F MOZ_Assert: Assertion failure: [unhandlable oom] Failed to allocate slots while tenuring., at /builds/worker/workspace/build/src/js/src/vm/JSContext.cpp:1586
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler: >>> REPORTING UNCAUGHT EXCEPTION FROM THREAD 1990 ("GeckoBackgroundThread")
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at android.database.CursorWindow.<init>(CursorWindow.java:108)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at org.mozilla.gecko.db.BrowserProvider.insertVisitForHistory(BrowserProvider.java:1874)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at org.mozilla.gecko.db.BrowserProvider.updateInTransaction(BrowserProvider.java:875)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at org.mozilla.gecko.db.AbstractTransactionalProvider.update(AbstractTransactionalProvider.java:226)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at android.content.ContentProvider$Transport.update(ContentProvider.java:362)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at android.content.ContentResolver.update(ContentResolver.java:1675)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at org.mozilla.gecko.db.LocalBrowserDB.updateVisitedHistory(LocalBrowserDB.java:765)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at org.mozilla.gecko.GlobalHistory.add(GlobalHistory.java:130)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at org.mozilla.gecko.GlobalHistory$1.run(GlobalHistory.java:165)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at android.os.Handler.handleCallback(Handler.java:790)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at android.os.Handler.dispatchMessage(Handler.java:99)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at android.os.Looper.loop(Looper.java:164)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler:     at org.mozilla.gecko.util.GeckoBackgroundThread.run(GeckoBackgroundThread.java:43)
07-20 23:33:56.839 16143 16205 E GeckoCrashHandler: Main thread (2) stack:
07-20 23:33:56.978 16143 16205 E GeckoCrashHandler:     android.support.design.widget.Snackbar.animateViewOut(Unknown Source:0)
07-20 23:33:56.979 16143 16205 E GeckoCrashHandler:     android.support.design.widget.Snackbar.hideView(Snackbar.java:606)
07-20 23:33:56.979 16143 16205 E GeckoCrashHandler:     android.support.design.widget.Snackbar$1.handleMessage(Snackbar.java:165)
07-20 23:33:56.979 16143 16205 E GeckoCrashHandler:     android.os.Handler.dispatchMessage(Handler.java:102)
07-20 23:33:56.979 16143 16205 E GeckoCrashHandler:     android.os.Looper.loop(Looper.java:164)
07-20 23:33:56.979 16143 16205 E GeckoCrashHandler:     android.app.ActivityThread.main(ActivityThread.java:6501)
07-20 23:33:56.979 16143 16205 E GeckoCrashHandler:     java.lang.reflect.Method.invoke(Native Method)
07-20 23:33:56.980 16143 16205 E GeckoCrashHandler:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
07-20 23:33:56.980 16143 16205 E GeckoCrashHandler:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

4GB of RAM is not enough it seems !

**Comment by mortalis13** [comment]
The error here is something about database and memory allocation for cursors. Cursors are objects with results of database queries. I suppose the app (Firefox) opens too much of these cursors (for tabs maybe) and doesn't close them, so the limited memory is overflowed (as explained in [this question](https://stackoverflow.com/questions/21219039/android-database-cursorwindowallocationexception-when-moving-a-cursor)). It's not the full device memory, it's a portion of it that the app uses for its work (maybe some tens or hundreds of MB).

I guess if you activate each tab manually the same error will happen.

I experimented with the WebIDE Console and found this method of extracting URLs:

    var _tabs = window.BrowserApp.tabs;
    for (var i=0; i<_tabs.length; i++) console.log(_tabs[i].currentURI.spec);

It will print the opened tabs URLs.
Didn't find exact reference for the properties in that script, just was trying to see which of them could show the real addresses instead of `about:blank` for discarded tabs (like `window[0].location` that I tried first).

It would be faster and more flexible that using the addon (in which case it would be necessary to change the range of exported tabs (1 to 50, 51 to 100...) and run it multiple times for a large number of tabs).
And so the addon is more appropriate for less extensive export.

**Comment by Niluge-KiWi** [comment]
I finally managed to export my tabs thanks to you!

Hopefully mozilla will add the `url` field to discarded tabs soon. Do you have a link to this issue? I could not find any on https://bugzilla.mozilla.org/

**Comment by mortalis13** [comment]
It should be this: https://bugzilla.mozilla.org/show_bug.cgi?id=1364610.
Glad you've resolved your problem.

**Comment by Niluge-KiWi** [comment]
OK, thanks for everything ! I'm closing the issue as we can't do anything better until Mozilla fixes the linked issue. And you provided me a workaround !
