### ISSUE TITLE
Not available on Android anymore

### ISSUE THREAD

**Issue by duttyend** [mortalis13/Tabs-Export-XPI-Android#7]
Dear dev,

I wanted to install your awesome Tabs Import/Export extensions on a new phone and wasn't able to install the Export one unfortunately (see screenshot).

Have a great day
![Screenshot_20190804-143625_Firefox](https://user-images.githubusercontent.com/7779942/62428343-535e9c80-b6c6-11e9-89a9-6c74f43f924b.png)

**Comment by mortalis13** [comment]
I've checked the addon page on my Android device and it doesn't give me that error.
Try to install Firefox Nightly on your phone and go to the the addon page and see if it lets you install it. 

If it works then your normal Firefox app has something in its settings that prevents correct Android detection. If you can, install a fresh Firefox app. 

Or check the UserAgent setting. For this navigate to `about:config` URL, then in the search field type `'general.useragent'`. You should see some settings matching the filter. Send me the screenshots with these values. With the UserAgent settings you can change the way the sites detect your browser type and version. So maybe it's detected as a desktop Firefox and gives you that message, because if you open the addon page in the desktop browser it gives you the same 'not available' error.
